#if !canImport(ObjectiveC)
import XCTest

extension ChanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChanceTests = [
        ("testAddition", testAddition),
        ("testDoubleApproximation", testDoubleApproximation),
        ("testEquatable", testEquatable),
        ("testInitialization", testInitialization),
        ("testProperties", testProperties),
        ("testSubtraction", testSubtraction),
    ]
}

extension ChancesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChancesTests = [
        ("testDictionaryProperty", testDictionaryProperty),
        ("testEquatable", testEquatable),
        ("testHashable", testHashable),
        ("testInitialization", testInitialization),
        ("testSubscript", testSubscript),
    ]
}

extension CustomDieTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CustomDieTests = [
        ("testChance", testChance),
        ("testEquatable", testEquatable),
        ("testHashable", testHashable),
        ("testInitialization", testInitialization),
        ("testReplacing", testReplacing),
        ("testRolling", testRolling),
        ("testSidesProperty", testSidesProperty),
    ]
}

extension DiceKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DiceKitTests = [
        ("test2d5plusd18minus4", test2d5plusd18minus4),
        ("testDicePlusTupleAdding", testDicePlusTupleAdding),
        ("testDiceRollable", testDiceRollable),
        ("testDiePlusDiceAdding", testDiePlusDiceAdding),
        ("testDiePlusDieAdding", testDiePlusDieAdding),
        ("testDiePlusIntAdding", testDiePlusIntAdding),
        ("testDiePlusTupleAdding", testDiePlusTupleAdding),
        ("testDieRollable", testDieRollable),
        ("testDieTimesIntMultiplication", testDieTimesIntMultiplication),
        ("testFileHandleOutputStream__INTERNAL_UTILITY_METHOD", testFileHandleOutputStream__INTERNAL_UTILITY_METHOD),
        ("testRollable", testRollable),
        ("testWeightedDieRollable", testWeightedDieRollable),
    ]
}

extension DiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DiceTests = [
        ("testAverageResult", testAverageResult),
        ("testCanReach", testCanReach),
        ("testChance", testChance),
        ("testChanceInRange", testChanceInRange),
        ("testCopying", testCopying),
        ("testDescription", testDescription),
        ("testDiceMinusIntSubtracting", testDiceMinusIntSubtracting),
        ("testDicePlusDiceAdding", testDicePlusDiceAdding),
        ("testDicePlusIntAdding", testDicePlusIntAdding),
        ("testDiceTimesIntMultiplication", testDiceTimesIntMultiplication),
        ("testEmptyStringParsing", testEmptyStringParsing),
        ("testEquatable", testEquatable),
        ("testInitialization", testInitialization),
        ("testInvalidStringParsing", testInvalidStringParsing),
        ("testMultipleDieAndMultipleModifierStringParsing", testMultipleDieAndMultipleModifierStringParsing),
        ("testMultipleModifierStringParsing", testMultipleModifierStringParsing),
        ("testMultipleRepeatedDieStringParsing", testMultipleRepeatedDieStringParsing),
        ("testMultipleSeparateDieStringParsing", testMultipleSeparateDieStringParsing),
        ("testNegativeMultipleDieStringParsing", testNegativeMultipleDieStringParsing),
        ("testRolling", testRolling),
        ("testRollingMultipleTimes", testRollingMultipleTimes),
        ("testSingleDieAndSingleModifierStringParsing", testSingleDieAndSingleModifierStringParsing),
        ("testSingleDieStringParsing", testSingleDieStringParsing),
        ("testSingleModifierStringParsing", testSingleModifierStringParsing),
    ]
}

extension DieSideTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DieSideTests = [
        ("testEquatable", testEquatable),
        ("testHashable", testHashable),
        ("testInitialization", testInitialization),
        ("testValueProperty", testValueProperty),
    ]
}

extension DieTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DieTests = [
        ("testAverageResultProperty", testAverageResultProperty),
        ("testCanReach", testCanReach),
        ("testChance", testChance),
        ("testChanceInRange", testChanceInRange),
        ("testComparable", testComparable),
        ("testCopying", testCopying),
        ("testDescription", testDescription),
        ("testDoubleAverageResultProperty", testDoubleAverageResultProperty),
        ("testEquatable", testEquatable),
        ("testInitialization", testInitialization),
        ("testInvalidStringParsing", testInvalidStringParsing),
        ("testMaximumResultProperty", testMaximumResultProperty),
        ("testMinAverageMax", testMinAverageMax),
        ("testMinimumResultProperty", testMinimumResultProperty),
        ("testMultipleDigitStringParsing", testMultipleDigitStringParsing),
        ("testRolling", testRolling),
        ("testRollingMultipleTimes", testRollingMultipleTimes),
        ("testSidesProperty", testSidesProperty),
        ("testSingleDigitStringParsing", testSingleDigitStringParsing),
        ("testStaticVarDice", testStaticVarDice),
    ]
}

extension NegationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NegationTests = [
        ("testAverageResult", testAverageResult),
        ("testCanReach", testCanReach),
        ("testDoubleNegation", testDoubleNegation),
        ("testInitialization", testInitialization),
        ("testMaximumResult", testMaximumResult),
        ("testMinimumResult", testMinimumResult),
        ("testProbabilities", testProbabilities),
        ("testRolling", testRolling),
    ]
}

extension WeightedDieTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WeightedDieTests = [
        ("testAverageResultProperty", testAverageResultProperty),
        ("testCanReachProperty", testCanReachProperty),
        ("testChance", testChance),
        ("testChanceInRange", testChanceInRange),
        ("testChancesProperty", testChancesProperty),
        ("testCopying", testCopying),
        ("testDoubleAverageResultProperty", testDoubleAverageResultProperty),
        ("testEquatable", testEquatable),
        ("testHashable", testHashable),
        ("testInitialization", testInitialization),
        ("testMaximumResultProperty", testMaximumResultProperty),
        ("testMinimumResultProperty", testMinimumResultProperty),
        ("testProbabilities", testProbabilities),
        ("testRolling", testRolling),
        ("testRollingMultipleTimes", testRollingMultipleTimes),
        ("testSidesProperty", testSidesProperty),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ChanceTests.__allTests__ChanceTests),
        testCase(ChancesTests.__allTests__ChancesTests),
        testCase(CustomDieTests.__allTests__CustomDieTests),
        testCase(DiceKitTests.__allTests__DiceKitTests),
        testCase(DiceTests.__allTests__DiceTests),
        testCase(DieSideTests.__allTests__DieSideTests),
        testCase(DieTests.__allTests__DieTests),
        testCase(NegationTests.__allTests__NegationTests),
        testCase(WeightedDieTests.__allTests__WeightedDieTests),
    ]
}
#endif
