#if !canImport(ObjectiveC)
import XCTest

extension ChanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChanceTests = [
        ("testDoubleApproximation", testDoubleApproximation),
        ("testEquatable", testEquatable),
        ("testInitialization", testInitialization),
        ("testProperties", testProperties),
    ]
}

extension ChancesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChancesTests = [
        ("testDictionaryProperty", testDictionaryProperty),
        ("testEquatable", testEquatable),
        ("testInitialization", testInitialization),
        ("testSubscript", testSubscript),
    ]
}

extension CustomDieTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CustomDieTests = [
        ("testEquatable", testEquatable),
        ("testHashable", testHashable),
        ("testInitialization", testInitialization),
        ("testReplacing", testReplacing),
        ("testRolling", testRolling),
        ("testSidesProperty", testSidesProperty),
    ]
}

extension DiceKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DiceKitTests = [
        ("testDieToDiceOperators", testDieToDiceOperators),
    ]
}

extension DiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DiceTests = [
        ("testAverageResult", testAverageResult),
        ("testEmptyStringParsing", testEmptyStringParsing),
        ("testInvalidStringParsing", testInvalidStringParsing),
        ("testMultipleDieAndMultipleModifierStringParsing", testMultipleDieAndMultipleModifierStringParsing),
        ("testMultipleModifierStringParsing", testMultipleModifierStringParsing),
        ("testMultipleRepeatedDieStringParsing", testMultipleRepeatedDieStringParsing),
        ("testMultipleSeparateDieStringParsing", testMultipleSeparateDieStringParsing),
        ("testSingleDieAndSingleModifierStringParsing", testSingleDieAndSingleModifierStringParsing),
        ("testSingleDieStringParsing", testSingleDieStringParsing),
        ("testSingleModifierStringParsing", testSingleModifierStringParsing),
    ]
}

extension DieSideTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DieSideTests = [
        ("testEquatable", testEquatable),
        ("testHashable", testHashable),
        ("testInitialization", testInitialization),
        ("testValueProperty", testValueProperty),
    ]
}

extension DieTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DieTests = [
        ("testAverageResultProperty", testAverageResultProperty),
        ("testCanReach", testCanReach),
        ("testComparable", testComparable),
        ("testCopying", testCopying),
        ("testDoubleAverageResultProperty", testDoubleAverageResultProperty),
        ("testEquatable", testEquatable),
        ("testInitialization", testInitialization),
        ("testInvalidStringParsing", testInvalidStringParsing),
        ("testMaximumResultProperty", testMaximumResultProperty),
        ("testMinAverageMax", testMinAverageMax),
        ("testMinimumResultProperty", testMinimumResultProperty),
        ("testMultipleDigitStringParsing", testMultipleDigitStringParsing),
        ("testRolling", testRolling),
        ("testSidesProperty", testSidesProperty),
        ("testSingleDigitStringParsing", testSingleDigitStringParsing),
        ("testStaticVarDice", testStaticVarDice),
    ]
}

extension WeightedDieTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WeightedDieTests = [
        ("testAverageResultProperty", testAverageResultProperty),
        ("testCanReachProperty", testCanReachProperty),
        ("testChancesProperty", testChancesProperty),
        ("testCopying", testCopying),
        ("testDoubleAverageResultProperty", testDoubleAverageResultProperty),
        ("testEquatable", testEquatable),
        ("testHashable", testHashable),
        ("testInitialization", testInitialization),
        ("testMaximumResultProperty", testMaximumResultProperty),
        ("testMinimumResultProperty", testMinimumResultProperty),
        ("testRolling", testRolling),
        ("testSidesProperty", testSidesProperty),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ChanceTests.__allTests__ChanceTests),
        testCase(ChancesTests.__allTests__ChancesTests),
        testCase(CustomDieTests.__allTests__CustomDieTests),
        testCase(DiceKitTests.__allTests__DiceKitTests),
        testCase(DiceTests.__allTests__DiceTests),
        testCase(DieSideTests.__allTests__DieSideTests),
        testCase(DieTests.__allTests__DieTests),
        testCase(WeightedDieTests.__allTests__WeightedDieTests),
    ]
}
#endif
