name: danger

# Controls when the action will run. This action runs Danger, so run on PRs only
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Run Danger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: danger/swift@3.12.3
        with:
          args: --use-github-checks --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
