name: danger

# Controls when the action will run. This action runs Danger, so run on PRs only
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Run Danger
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.3"
      - run: swift --version #make sure we have the version of swift we want, and that it can be seen in the logs
      - run: python3 scripts/include_dev_dependencies.py
      - run: npm install -g danger
      - run: swift build
      - run: swift run danger-swift ci --use-github-checks --verbose
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
