name: Deploy Docs

on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    name: Deploy
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
    - run: swift --version
    - name: Install jazzy
      run: gem install jazzy
    - name: Run jazzy
      run: jazzy -o newdocs
    - name: Checkout gh-pages
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: ghp
    - name: Process docs
      run: |
        VERSION=${GITHUB_REF:#refs/tags/v} #lops of that part from the beginning of the string, could be ${GITHUB_REF:11} to chop off 11 characters
        mkdir ghp/docs/v$VERSION
        mv newdocs/* ghpd/docs/v$VERSION
        cd ghp
        echo 'section > section > p > img { margin-top: 4em; margin-right: 2em; }' >> docs/v$VERSION/css/jazzy.css
        bash ../scripts/updateLatestDocs.sh $VERSION
    - name: Push updated docs
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Add documentation for version $VERSION"
        git push
