name: Main

# Controls when the action will run. Since this action runs only tests, and Danger/deploy is run via Travis, run on pushes and PRs
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test Swift ${{ matrix.swift }}.x on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
          #swift: ["4.2", "5.0", "5.1", "5.2", "5.3", "5.4", "5.5"] #setup-swift finds the latest bug fix version
        exclude:
          - os: macos-latest
            swift: "4.2" #Swift 4.2 is no longer supported on macOS 10.15 (macOS-latest)
#          - os: macos-latest
#            swift: "5.2" #Not sure why, but this isn't working
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
        #with:
          #swift-version: ${{ matrix.swift }}
      - run: swift --version #make sure we have the version of swift we want, and that it can be seen in the logs
      - run: swift test
