# This is a basic workflow to help you get started with Actions

name: PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test Swift ${{ matrix.swift }}.x on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-16.04, ubuntu-latest]
        swift: ["4.2", "5.0", "5.1", "5.2", "5.3"]
        exclude:
          - os: macos-latest
            swift: "5.2"
          - os: macos-latest
            swift: "4.2"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - run: swift --version
      - run: swift test
  danger:
    name: Danger
    runs-on: macos-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.2"
    - run: swift --version
    - name: Install Danger
      run: |
        python3 scripts/include_dev_dependencies.py
        npm install -g danger
        swift build
    - name: Run Danger
      run: swift run danger-swift ci
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Rehide dev dependencies
      run: python3 scripts/remove_dev_dependencies.py
