name: Push (non-master)

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    name: Test Swift ${{ matrix.swift }}.x on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-16.04, ubuntu-latest]
        swift: ["4.2", "5.0", "5.1", "5.2"]
        exclude:
          - os: macos-latest
            swift: "4.2"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - run: swift --version
      - run: swift test
