name: tests

# Controls when the action will run. Since this action runs only tests, run on pushes and PRs
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test Swift ${{ matrix.swift }}.x on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
        #os: [macos-10.15, macos-11, macos-12, ubuntu-18.04, ubuntu-20.04]
        swift: ["4.2", "5.0", "5.1", "5.2", "5.3", "5.4", "5.5", "5.6"] #setup-swift finds the latest bug fix version
        exclude:
          - os: macos-10.15
            swift: "4.2"
          - os: macos-10.15
            swift: "5.1"
          - os: macos-10.15
            swift: "5.2"
          - os: macos-11 #the vast majority of these fail, so we exclude the OS and include the specific Swift versions
          - os: macos-12
          - os: ubuntu-20.04
            swift: "4.2"
          - os: ubuntu-20.04
            swift: "5.0"
          - os: ubuntu-20.04
            swift: "5.1"
          - os: ubuntu-22.04 #Not supported by setup-swift
        include:
          - os: macos-11
            swift: "5.5"
          - os: macos-11
            swift: "5.6"
          - os: macos-12
            swift: "5.5"
          - os: macos-12
            swift: "5.6"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - run: |
          swift --version
          echo "Using \`$(swift --version | head -n 1)\`" >> $GITHUB_STEP_SUMMARY
      - run: swift test --parallel --xunit-output output.xml
        if: startsWith(matrix.os, 'ubuntu')
      - run: swift test
        if: startsWith(matrix.os, 'macos')
      - uses: test-summary/action@v1
        if: always() && startsWith(matrix.os, 'ubuntu')
        with:
          paths: output.xml
          show: fail #none | all | (fail)?,(pass)?,(skip)?
